### PR TITLE
typo with firsmod and imports shall come after documentation

### PR DESCRIPTION
**Pull request by peshay**

### CODE REVIEW

**Comment by relaxdiego** [comment]
Please add a footnote crediting yourself for the edits and feel free to link to your site or LinkedIn page.

**Comment by peshay** [comment]
for example like this  <sup>edited by [Andreas Hubert](https://www.linkedin.com/in/peshay/)</sup> ?

**Comment by relaxdiego** [comment]
How about at the foot of the page. Like "Co-written by Andreas Huber" or something like that.

**Comment by peshay** [comment]
Okay, what about now? :) 
I added ANSIBLE_METADATA. About the __future__ import you can decide if you get this error:
```
hacking/test-module -m lib/ansible/modules/vault/firstmod.py -a "url=https://www.google.com dest=/tmp/ansibletest.txt"
***********************************
RAW OUTPUT

  File "/Users/ahu/debug_dir/ansible_module_firstmod.py", line 40
    from __future__ import (absolute_import, division)
SyntaxError: from __future__ imports must occur at the beginning of the file
```
or you put it before the DOCUMENTATION and get this error
```
test/sanity/validate-modules/validate-modules lib/ansible/modules/vault/firstmod.py                                   
lib/ansible/modules/vault/firstmod.py:17:0: E106 Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA.
```

**Pull request merged**
